# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform  
  
on: 
  workflow_dispatch: 
  
  push:  
    tags:  
      - 'v*' # 当推送标签时触发，例如 v1.0.0  
  
env:  
  BUILD_TYPE: Release  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - uses: actions/checkout@v4  

    - name: apt install libboost-all-dev  
      run: |  
        #sudo apt-get update  
        #sudo apt-get install -y libboost-all-dev  
        echo "install boost"
  
    - name: Configure CMake  
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}  
  
    - name: Build  
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}  
  
    - name: Test  
      working-directory: ${{github.workspace}}/build  
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Create release archive  
      run: tar -czvf testboost.tar.gz -C build testboost  
    
    - name: Extract version from tag  
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
  
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref_name }} # 使用推送的标签名，如v1.0.0
        release_name: Release ${{ github.ref_name }}
        body: "Release description" 
        draft: false
        prerelease: false
  
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./testboost.tar.gz
        asset_name: testboost.tar.gz
        asset_content_type: application/gzip
