name: Workflow dispatch demo
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - error  

      version-override:
        description: 'version string'
        required: false
        default: ""
        type: string
          

  push:
   branches:
     - "main"
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Echo a message
      run: |-
        echo "Running the build with log level:${{ github.event.inputs.logLevel }}"
        echo "Running the build with version string:${{ github.event.inputs.version-override }}"

