name: Workflow dispatch demo  
on:  
  workflow_dispatch:  
    inputs:  
      logLevel:  
        description: 'Log level'  
        required: true  
        default: 'warning'  
        type: choice  
        options:  
          - info  
          - warning  
          - error  
      version-override:  
        description: 'Version string'  
        required: false  
        default: ''  
        type: string  
  
jobs:  
  check_workflow_inputs:  
    name: Check Manual Run Inputs  
    runs-on: ubuntu-latest  
    outputs:  
      versionArg: ${{ steps.set_version.outputs.versionArg }}  
  
    steps:  
      - name: Set versionArg output  
        id: set_version  
        shell: bash  
        run: |  
          VERSION_ARG=""  
          if [ -n "$VERSION_OVERRIDE" ]; then  
            VERSION_ARG="$VERSION_OVERRIDE-SNAPSHOT"  
          fi  
          echo "Setting versionArg output to: $VERSION_ARG"  
          echo "::set-output name=versionArg::$VERSION_ARG"  
        env:  
          VERSION_OVERRIDE: ${{ github.event.inputs.version-override }}  
  
  build:  
    name: Build  
    runs-on: ubuntu-latest  
    needs: [check_workflow_inputs]  
    steps:  
      - name: Echo versionArg  
        run: |  
          echo "Building with versionArg: ${{ needs.check_workflow_inputs.outputs.versionArg }}"
