name: Workflow dispatch demo  
on:  
  workflow_dispatch:  
    inputs:  
      logLevel:  
        description: 'Log level'  
        required: true  
        default: 'warning'  
        type: choice  
        options:  
          - info  
          - warning  
          - error    
  
      version-override:  
        description: 'version string'  
        required: false  
        default: ''  
        type: string  
  
  push:  
    branches:  
      - main  
  
jobs:    
  check_workflow_inputs:    
    name: Check Manual Run Inputs    
    runs-on: ubuntu-latest    
    outputs:    
      versionArg: ${{ steps.manual_input_check.outputs.versionArg }}    
    
    steps:    
      - name: Check Manual Run Inputs  
        id: manual_input_check  
        run: |  
          echo "This is the check_workflow_inputs job"  
          echo "VERSION_OVERRIDE: $VERSION_OVERRIDE"  
          VERSION_ARG=""  
          if [ -n "$VERSION_OVERRIDE" ]; then  
            VERSION_ARG="-Pversion=$VERSION_OVERRIDE"  
            echo "::set-output name=versionArg::$VERSION_ARG"  
          fi  
          echo "Setting versionArg output to: $VERSION_ARG"  
        env:  
          VERSION_OVERRIDE: ${{ github.event.inputs.version-override }}  
  
  build:  
    name: Build  
    runs-on: ubuntu-latest  
    needs: [check_workflow_inputs]  
    env:  
      VERSION_ARG: ${{ needs.check_workflow_inputs.outputs.versionArg }}  
    steps:  
    - name: Echo a message  
      run: |  
        echo "Running the build with log level: ${{ github.event.inputs.logLevel }}"  
        echo "Running the build with version string: ${{ github.event.inputs.version-override }}"  
        echo "VERSION_ARG: $VERSION_ARG"
