name: Workflow dispatch demo
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - error  

      version-override:
        description: 'version string'
        required: false
        default: ""
        type: string
          

  push:
   branches:
     - "main"
    
jobs:  
  check_workflow_inputs:  
    name: Check Manual Run Inputs  
    runs-on: ubuntu-latest  
    outputs:  
      versionArg: ${{ steps.manual_input_check.outputs.versionArg }}  
  
    steps:  
      - name: Check Manual Run Inputs # 注意这里添加了冒号  
        id: manual_input_check  
        run: | # 这里使用 | 来表示多行字符串（如果需要的话）  
          echo "This is the check_workflow_inputs job"  
          # 这里可以添加其他命令来检查手动输入的参数  
          # 比如，假设您有一个输入参数叫 version，您可能会这样做：  
          # versionArg=$(echo "$VERSION_INPUT" | tr '[:upper:]' '[:lower:]')  
          # echo "::set-output name=versionArg::$versionArg"  
          # 注意：上述示例中的 VERSION_INPUT 需要作为工作流的输入来定义
    
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [check_workflow_inputs]
    env:
      VERSION_ARG: ${{ needs.check_workflow_inputs.outputs.versionArg }}
    steps:
    - name: Echo a message
      run: |-
        echo "Running the build with log level:${{ github.event.inputs.logLevel }}"
        echo "Running the build with version string:${{ github.event.inputs.version-override }}"
        echo "VERSION_ARG: ${{ env.VERSION_ARG }}"

